# Site settings
title: Fab Lab Cascina
tag_text: Fab Lab Cascina
description: Fab Lab Cascina is a digital fabrication laboratory in the middle of Tuscany, planet Earth

# Build settings
markdown: kramdown

exclude: ["README.md"]
